run:
  timeout: 3m
  skip-files:
    - "internal/pkg/util/user/cgo_lookup_unix.go"

linters:
  disable-all: true
  enable-all: false
  enable:
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - dupl
    - gofumpt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - maintidx
    - misspell
    - nakedret
    - revive
    - staticcheck

linters-settings:
  misspell:
    locale: US

issues:
  max-per-linter: 0
  max-same-issues: 0
